[[commands]]
id = "browser_open"
action = "ahk"
exe_path = "ahk/Run browser.exe"
sounds = ["ok1", "ok2", "ok3"]
phrases = [
    "открой браузер",
    "запусти браузер",
    "открой хром",
    "запусти хром",
    "открой гугл хром",
    "запусти гугл хром",
    "включи браузер",
    "браузер открой",
    "нужен браузер",
    "мне нужен браузер",
]

[[commands]]
id = "browser_close"
action = "ahk"
exe_path = "ahk/Close browser.exe"
sounds = ["ok1", "ok2", "ok3", "ok4"]
phrases = [
    "закрой браузер",
    "закрой все браузеры",
    "выключи браузер",
    "убери браузер",
    "закрой хром",
    "выключи хром",
    "закрой гугл хром",
    "браузер закрой",
    "сверни браузер",
]

[[commands]]
id = "open_google"
action = "ahk"
exe_path = "ahk/Run website.exe"
exe_args = ["http://google.com"]
sounds = ["ok1", "ok2", "ok3", "ok4"]
phrases = [
    "открой гугл",
    "открой гугл поиск",
    "запусти гугл",
    "перейди в гугл",
    "перейди на гугл",
    "открой поисковик",
    "зайди в гугл",
    "гугл поиск",
    "поиск гугл",
]